
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url:
      env("DATABASE_URL") ||
      (process.env.RAILWAY_VOLUME_MOUNT_PATH
        ? `file:${process.env.RAILWAY_VOLUME_MOUNT_PATH.replace(/\/$/, "")}/dev.db`
        : "file:./dev.db"),
  },
});
